# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# Build and test, publish on release-tag.
name: CI

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  release:
    types:
    - created

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm clean-install
    - run: npm run build-grammar
    - run: npm run build
    - run: npm test
    - name: Publish
      # Publish on release tag.
      # Only publish once for the matrix, not for every node version.
      if: success() && startsWith(github.ref, 'refs/tags/') && matrix.node-version == '18.x'
      run: npm run publish
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
